openapi: 3.0.3
info:
  title: RFE Workspaces API
  version: 0.3.1
servers:
  - url: /api
paths:
  /projects/{projectName}/auth/github/install:
    post:
      summary: Link SSO user to GitHub installation (per-user App)
      parameters:
        - in: path
          name: projectName
          required: true
          schema: { type: string }
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required: [installationId]
              properties:
                installationId: { type: integer }
      responses:
        '200': { description: Linked }
  /projects/{projectName}/users/forks:
    get:
      summary: List user forks for an upstream repo (RBAC-scoped)
      parameters:
        - in: path
          name: projectName
          required: true
          schema: { type: string }
        - in: query
          name: upstreamRepo
          required: true
          schema: { type: string }
      responses:
        '200': { description: OK }
    post:
      summary: Create a fork of the upstream umbrella repo for the user
      parameters:
        - in: path
          name: projectName
          required: true
          schema: { type: string }
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required: [upstreamRepo]
              properties:
                upstreamRepo: { type: string }
      responses:
        '202': { description: Fork creation requested }
  /projects/{projectName}/repo/tree:
    get:
      summary: Fetch repo tree entries via backend proxy
      parameters:
        - in: path
          name: projectName
          required: true
          schema: { type: string }
        - in: query
          name: repo
          required: true
          schema: { type: string }
        - in: query
          name: ref
          required: true
          schema: { type: string }
        - in: query
          name: path
          required: false
          schema: { type: string }
      responses:
        '200': { description: OK }
  /projects/{projectName}/repo/blob:
    get:
      summary: Fetch blob (text) via backend proxy
      parameters:
        - in: path
          name: projectName
          required: true
          schema: { type: string }
        - in: query
          name: repo
          required: true
          schema: { type: string }
        - in: query
          name: ref
          required: true
          schema: { type: string }
        - in: query
          name: path
          required: true
          schema: { type: string }
      responses:
        '200': { description: OK }
  /projects/{projectName}/rfe-workflows:
    post:
      summary: Create workspace (RFE workflow) in project
      parameters:
        - in: path
          name: projectName
          required: true
          schema: { type: string }
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required: [upstreamRepoUrl, workspaceName]
              properties:
                upstreamRepoUrl: { type: string }
                workspaceName: { type: string }
      responses:
        '201': { description: Created }
  /projects/{projectName}/rfe-workflows/{id}/specify:
    post:
      summary: Run Specify on canonical branch (using invoking user token)
      parameters:
        - in: path
          name: projectName
          required: true
          schema: { type: string }
        - in: path
          name: id
          required: true
          schema: { type: string }
      responses:
        '202': { description: Accepted }
  /projects/{projectName}/rfe-workflows/{id}/sessions:
    post:
      summary: Start runner session for workflow (select runner type)
      parameters:
        - in: path
          name: projectName
          required: true
          schema: { type: string }
        - in: path
          name: id
          required: true
          schema: { type: string }
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                runnerType:
                  type: string
                  enum: [claude, openai, localexec]
                forkUrl: { type: string }
                inputRepo: { type: string }
                inputBranch: { type: string }
                outputRepo: { type: string }
                outputBranch: { type: string }
              description: forkUrl is required for RFE sessions; input/output may be optional for non‑RFE sessions
      responses:
        '201': { description: Created }
  /projects/{projectName}/sessions/{sessionId}/prs:
    post:
      summary: Create PRs for changed repositories (umbrella + submodules)
      parameters:
        - in: path
          name: projectName
          required: true
          schema: { type: string }
        - in: path
          name: sessionId
          required: true
          schema: { type: string }
      responses:
        '202': { description: Accepted }
  /projects/{projectName}/sessions/{sessionId}/messages:
    get:
      summary: Stream or fetch session messages (from S3; supports partial fragments)
      parameters:
        - in: path
          name: projectName
          required: true
          schema: { type: string }
        - in: path
          name: sessionId
          required: true
          schema: { type: string }
      responses:
        '200': { description: OK }
  
