# golangci-lint configuration for vTeam operator
# Compatible with golangci-lint v2.x
#
# Pragmatic configuration for Kubernetes operator development.

version: "2"

run:
  timeout: 5m

linters:
  enable:
    - govet
    - ineffassign
    - staticcheck
    - unused
    - misspell
  disable:
    - errcheck      # Disabled: too many false positives with defer cleanup

  settings:
    staticcheck:
      checks: ["all", "-SA1019"]  # Disable deprecation warnings only

  exclusions:
    rules:
      # Exclude linters from test files
      - path: _test\.go
        linters:
          - staticcheck
          - govet

      # Allow type assertions in K8s reconciliation (intentional pattern)
      - path: internal/handlers/
        text: "type assertion"

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
  new: false
